# Generated by Django 2.2.4 on 2019-08-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateField(verbose_name='Date Published'),
        ),
    ]
